// Header
export { default as LOGO } from './header/logo.png'
export { default as DROPDOWN_ICON } from './header/dropdown-icon.png'
export { default as LOGIN_BTN_OUTLINE } from './header/login-btn-outline.png'
export { default as COIN_ICON } from './header/coin-icon.png'
export { default as DEFAULT_HEADER_AVATAR } from './header/default-header-avatar.png'

// Footer
export { default as COPYRIGHT } from './footer/copyright.png'
export { default as FOOTER_BG } from './footer/footer-bg.png'

// Home
export { default as LOGO_BANNER } from './home/logo-banner.png'
export { default as GRADIENT_TITLE } from './home/gradient-title.png'
export { default as NEXT_RACE_BORDER } from './home/next-race-border.png'
export { default as ARROW_RIGHT } from './home/arrow-right.png'
export { default as OPEN_RACE_FRAME } from './home/open-race-frame.png'
export { default as OPEN_RACE_TOP_FRAME } from './home/open-race-top-frame.png'
export { default as OPEN_RACE_BTN_BORDER } from './home/open-race-btn-border.png'
export { default as OPEN_RACE_CLASS } from './home/open-race-class.png'
export { default as OPEN_RACE_OVERLAY } from './home/open-race-overlay.png'
export { default as OPEN_RACE_BG } from './home/open-race-bg.png'
export { default as BLUE_ARROW_LEFT } from './home/blue-arrow-left.png'
export { default as BLUE_ARROW_RIGHT } from './home/blue-arrow-right.png'
export { default as JOIN_NOW_BG } from './home/join-now-bg.png'
export { default as JOIN_NOW_BLOCK } from './home/join-now-block.png'
export { default as JOIN_NOW_BTN_BG } from './home/join-now-btn-bg.png'
export { default as JOIN_NOW_HORSE } from './home/join-now-horse.png'
export { default as JOIN_NOW_HORSE_SHADOW } from './home/join-now-horse-shadow.png'
export { default as TOP_HORSE_BG } from './home/top-horse-bg.png'
export { default as TOP_HORSE_BRONZE_CIRCLE } from './home/top-horse-bronze-circle.png'
export { default as TOP_HORSE_BRONZE_CROWN } from './home/top-horse-bronze-crown.png'
export { default as TOP_HORSE_FIRST_LEFT_FRAME } from './home/top-horse-first-left-frame.png'
export { default as TOP_HORSE_FIRST_RIGHT_FRAME } from './home/top-horse-first-right-frame.png'
export { default as TOP_HORSE_GOLD_CIRCLE } from './home/top-horse-gold-circle.png'
export { default as TOP_HORSE_GOLD_CROWN } from './home/top-horse-gold-crown.png'
export { default as TOP_HORSE_LEFT_STICK } from './home/top-horse-left-stick.png'
export { default as TOP_HORSE_RIGHT_STICK } from './home/top-horse-right-stick.png'
export { default as TOP_HORSE_SECOND_LEFT_FRAME } from './home/top-horse-second-left-frame.png'
export { default as TOP_HORSE_SECOND_RIGHT_FRAME } from './home/top-horse-second-right-frame.png'
export { default as TOP_HORSE_SILVER_CIRCLE } from './home/top-horse-silver-circle.png'
export { default as TOP_HORSE_SILVER_CROWN } from './home/top-horse-silver-crown.png'
export { default as ACHIEVEMENT } from './home/achievement.png'
export { default as TOP_STABLE_GOLD_MEDAL } from './home/top-stable-gold-medal.png'
export { default as TOP_STABLE_SILVER_MEDAL } from './home/top-stable-silver-medal.png'
export { default as TOP_STABLE_BRONZE_MEDAL } from './home/top-stable-bronze-medal.png'
export { default as TOP_STABLE_FRAME } from './home/top-stable-frame.png'
export { default as TOP_STABLE_TOP_FRAME } from './home/top-stable-top-frame.png'
export { default as TOP_STABLE_CIRCLE } from './home/top-stable-circle.png'
export { default as SLOT_FRAME } from './home/slot-frame.png'

// Home mock
export { default as NEXT_RACE_THUMBNAIL } from './home-mock/next-race-thumbnail.png'
export { default as OPEN_RACE_THUMBNAIL } from './home-mock/open-race-thumbnail.png'
export { default as TOP_HORSE } from './home-mock/top-horse.png'
export { default as TOP_STABLE_AVATAR } from './home-mock/top-stable-avatar.png'

// Race
export { default as MAGNIFYING_GLASS } from './race/magnifying-glass.png'
export { default as ORANGE_LINE } from './race/orange-line.png'
export { default as FILTER_BTN_BG } from './race/filter-btn-bg.png'
export { default as FILTER_ICON } from './race/filter-icon.png'
export { default as AVATAR_CHOOSE_HORSE_BG } from './race/avatar-choose-horse-bg.png'
export { default as BOARD_VIEW_TIME } from './race/board-view-time.png'
export { default as CARET_LEFT } from './race/caret-left.png'
export { default as ORANGE_LINE_LEAN_LEFT } from './race/orange-line-lean-left.png'
export { default as POLYGON } from './race/polygon.png'
export { default as ORANGE_LINE_LEAN_RIGHT } from './race/orange-line-lean-right.png'
export { default as BTN_VIEW_RACE_2D } from './race/btn-view-race-2d.png'
export { default as AVATAR_HORSE } from './race/avatar-horse.png'
export { default as BACKGROUND_HORSE } from './race/background-horse.png'
export { default as RACETRACK } from './race/racetrack.png'
export { default as TRIANGLE_YELLOW } from './race/triangle-yellow.png'
export { default as NUMBER_HORSE } from './race/number-horse.png'
export { default as IMAGE_HORSE } from './race/image-horse.png'
export { default as COLUMN_YELLOW } from './race/column-yellow.png'
export { default as BTN_REPLAY } from './race/btn-replay.png'
export { default as HORSE_RANK_AVATAR_FRAME } from './race/horse-rank-avatar-frame.png'
export { default as CROWN_GOLD } from './race/crown-gold.png'
export { default as CROWN_SILVER } from './race/crown-silver.png'
export { default as CROWN_BRONZE } from './race/crown-bronze.png'
export { default as CROWN_GOLD_BORDER } from './race/crown-gold-border.png'
export { default as CROWN_SILVER_BORDER } from './race/crown-silver-border.png'
export { default as CROWN_BRONZE_BORDER } from './race/crown-bronze-border.png'

// Login
export { default as METAMASK_LOGIN_BTN } from './login/metamask-login-btn.png'
export { default as TRUSTWALLET_LOGIN_BTN } from './login/trustwallet-login-btn.png'

// Horse
export { default as YELLOW_LINE } from './horse/yellow-line.png'
export { default as GREY_LINE } from './horse/grey-line.png'
export { default as HORSE_AVATAR_BG } from './horse/horse-avatar-bg.png'
export { default as FLASH_ICON } from './horse/flash-icon.png'
export { default as RECOVERY_ICON } from './horse/recovery-icon.png'
export { default as LEVEL_FRAME } from './horse/level-frame.png'
export { default as CLOSE_BTN } from './horse/close-btn.png'

// Horse mock
export { default as HORSE_AVATAR } from './horse-mock/horse-avatar.png'

// Profile
export { default as CAMERA_ICON } from './profile/camera-icon.png'
export { default as ONE_LINE_YELLOW } from './profile/one-line-yellow.png'
export { default as SETTING_ICON } from './profile/setting-icon.png'
export { default as SHARE_ICON } from './profile/share-icon.png'
export { default as UPLOAD_BG_BTN } from './profile/upload-bg-btn.png'

// Profile mock
export { default as AVATAR_BG } from './profile-mock/avatar-bg.png'
export { default as MY_HORSE_AVATAR } from './profile-mock/my-horse-avatar.png'

// Global
export { default as SECONDARY_BTN_OUTLINE } from './secondary-btn-outline.png'
export { default as MINI_LOGO } from './mini-logo.png'
export { default as ONE_LINE } from './one-line.png'
export { default as TWO_LINE } from './two-line.png'
export { default as RACE_HOME } from './race-home.png'
export { default as ACTIVE_TAG_BG } from './active-tag-bg.png'
export { default as INACTIVE_TAG_BG } from './inactive-tag-bg.png'
export { default as NEXT_RACE_BOTTOM_FRAME } from './next-race-bottom-frame.png'
